language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=SwivelCake
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8

matrix:
  include:
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.8

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
